# @package _global_
defaults:
  - _self_

model_name: Multimodal_CONCAT

PolyMNIST:
  max_epochs: 100
  batch_size: 256
  lr_downstream: 0.001
  weight_decay_downstream: 0
  # model specific
  embedding_size: 512
  use_imputer: False
  imputer_name: MoPoE
  imputer_checkpoint: /home/siyi/project/mm/result/Dynamic_project/PM23/MoPoE_MMNIST_2025_04_01_17_18_11_421525/checkpoints/0299/mm_vae

  max_epochs_pretrain: 300
  lr_pretrain: 0.001
  weight_decay_pretrain: 0


MST:
  max_epochs: 20
  batch_size: 256
  lr_downstream: 0.001
  weight_decay_downstream: 0
  # model specific
  embedding_size: 32
  use_imputer: False
  imputer_name: MoPoE
  imputer_checkpoint: /home/siyi/project/mm/result/Dynamic_project/MS6/MNIST_SVHN_Text/joint_elbo/non_factorized/laplace_laplace_categorical/SVHN_MNIST_text_2025_05_05_14_13_16_648881/checkpoints/0199/mm_vae

  max_epochs_pretrain: 200
  lr_pretrain: 0.001
  weight_decay_pretrain: 0


CelebA:
  max_epochs: 20
  batch_size: 256
  lr_downstream: 0.001
  weight_decay_downstream: 0
  # model specific
  embedding_size: 32
  use_imputer: False
  imputer_name: MoPoE
  imputer_checkpoint: /home/siyi/project/mm/result/Dynamic_project/CA11/CelebA/joint_elbo/factorized/laplace_categorical/CelebA_2025_05_15_18_15_43_805671/checkpoints/0199/mm_vae

  max_epochs_pretrain: 200
  lr_pretrain: 0.001
  weight_decay_pretrain: 0


DVM:
  max_epochs: 300
  batch_size: 256
  lr_downstream: 0.0003
  weight_decay_downstream: 0
  # model specific
  embedding_size: 256
  use_imputer: False
  imputer_name: TIP
  imputer_checkpoint: /vol/biomedic3/sd1523/project/mm/result/TIP_results/D20/MaskAttn_ran00spec05_dvm_0104_0938/checkpoint_last_epoch_499.ckpt

  max_epochs_pretrain: 300
  lr_pretrain: 0.001
  weight_decay_pretrain: 0


CAD:
  max_epochs: 300
  batch_size: 128
  lr_downstream: 0.0003
  weight_decay_downstream: 0
  # model specific
  embedding_size: 256
  use_imputer: False
  imputer_name: TIP
  imputer_checkpoint: /vol/biomedic3/sd1523/project/mm/result/TIP_results/FC7/Tip_05_3e4_CAD_0118_1106/checkpoint_last_epoch_499.ckpt

  max_epochs_pretrain: 300
  lr_pretrain: 0.001
  weight_decay_pretrain: 0


Infarction:
  max_epochs: 300
  batch_size: 128
  lr_downstream: 0.0003
  weight_decay_downstream: 0
  # model specific
  embedding_size: 256
  use_imputer: False
  imputer_name: TIP
  imputer_checkpoint: /vol/biomedic3/sd1523/project/mm/result/TIP_results/FC7/Tip_05_3e4_CAD_0118_1106/checkpoint_last_epoch_499.ckpt

  max_epochs_pretrain: 300
  lr_pretrain: 0.001
  weight_decay_pretrain: 0