# @package _global_
defaults:
  - _self_

dataset_name: CelebA
data_base_postfix: MoPoE/CelebA

target: CelebA

break_avoidance: False
image_size: 64
num_classes: 2
num_modalities: 2
modality_names: ['img', 'text']
len_sequence: 256  # text length
eval_metric: auc
alphabet: 

DATA_train: train
DATA_val: val
DATA_test: test
missing_train: 'none'   # numbers present missing modalities
missing_val: 'none'
missing_test: 'none'

DATA_train_short:
DATA_val_short:
DATA_test_short:
missing_train_short:
missing_val_short:
missing_test_short: